name: Test and Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
permissions: write-all
jobs:
  assess:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run tests
        continue-on-error: true
        run: pytest

      - name: Record test results
        if: '!cancelled()'
        run: |
          pytest -r N --tb=no

      - name: Run linter
        continue-on-error: true
        if: '!cancelled()'
        run: pylint --fail-under=8 */*.py --ignore-patterns "test_.+.py" --disable=R0801 