name: Assessment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions: write-all
jobs:
  assess:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run tests
        continue-on-error: true
        run: pytest

      - name: Record test results
        if: '!cancelled()'
        run: |
          pytest -r N --tb=no > .util/marking.txt || true

      - name: Run linter
        continue-on-error: true
        if: '!cancelled()'
        run: pylint --fail-under=8 */*.py --ignore-patterns "test_.+.py" --disable=R0801 

      - name: Record linter results
        if: '!cancelled()'
        run: |
          pylint --fail-under=0 --score=y --reports=n */*.py --disable=R0801 --ignore-patterns "test_.+.py" >> .util/marking.txt || true

      - name: Push results
        if: '!cancelled()'
        run: |
          git add .util/marking.txt
          git commit -m "Lint"
          git push